# Generated by Django 4.1.13 on 2025-09-06 14:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('image_filename', models.CharField(blank=True, help_text='Extracted filename (auto-filled from upload or URL)', max_length=200, null=True)),
                ('image_url', models.CharField(blank=True, help_text='Enter full URL (https://...) or relative static path (e.g. images/Maldives.jpg)', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Trending', 'Trending'), ('Rooms', 'Rooms'), ('Iconic Cities', 'Iconic Cities'), ('Hot Beaches', 'Hot Beaches'), ('Mountains', 'Mountains'), ('Castles', 'Castles'), ('Pools', 'Pools'), ('Islands', 'Islands'), ('Camping', 'Camping'), ('Farms', 'Farms'), ('Arctic', 'Arctic'), ('Ships', 'Ships'), ('Domes', 'Domes')], default='Trending', max_length=50)),
                ('geometry_type', models.CharField(choices=[('Point', 'Point')], default='Point', max_length=20)),
                ('geometry_coordinates', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
