# Generated by Django 4.1.13 on 2025-09-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image_upload',
        ),
    ]
