# Generated by Django 4.1.13 on 2025-09-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_image_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
